# agent
agent_name: dmc_state_agent

# env setting
env:
  env: DMC
  game: hopper_hop
  base_seed: 0
  n_skip: 2
  n_stack: 1
  max_episode_steps: 1000
  clip_reward: False
  obs_shape: [10]
  episodic: False

rl:
  discount: 0.99
  unroll_steps: 5
  td_steps: 5
  auto_td_steps: 30000
  td_lambda: 0.95

# optimizer
optimizer:
  type: SGD
  lr: 0.2
  lr_warm_up: 0.01
  lr_decay_type: none
  lr_decay_rate: 0.1
  lr_decay_steps: 100000
  weight_decay: 1e-4
  momentum: 0.9

# priority of data
priority:
  use_priority: True
  priority_prob_alpha: 1.0
  priority_prob_beta: 1.0
  min_prior: 0.000001

# training
train:
  load_model_path: ''
  batch_size: 256
  training_steps: 200000
  offline_training_steps: 20000
  start_transitions: 2000

  eval_n_episode: 10
  eval_interval: 5000

  self_play_update_interval: 100
  reanalyze_update_interval: 200
  save_ckpt_interval: 10000

  mini_batch_size: 256
  reanalyze_ratio: 1.0

  reward_loss_coeff: 1.0
  value_loss_coeff: 0.5
  policy_loss_coeff: 1.0
  consistency_coeff: 2.0
  decorrelation_coeff: 0.01
  off_diag_coeff: 5e-3
  entropy_coeff: 5e-3

  max_grad_norm: 5
  change_temperature: True

  periodic_reset: False
  value_reanalyze: False
  path_consistency: False
  use_decorrelation: False
  value_policy_detach: False
  optimal_Q: False
  v_num: 1
  value_target: 'mixed'
  use_IQL: False
  IQL_weight: 0.5
  start_use_mix_training_steps: 4e4
  mixed_value_threshold: 2e4

# self-play data collection
data:
  num_envs: 4
  buffer_size: 200000
  total_transitions: 200000
  top_transitions: 2e5
  trajectory_size: 100
  save_video: False
  save_as_dataset: False

# MCTS
mcts:
  language: cython
  num_simulations: 32
  num_top_actions: 16
  num_sampled_actions: 16
  c_visit: 50
  c_scale: 0.1
  value_minmax_delta: 0.01
  mpc_horizon: 1
  vis: ['print']
  use_mppi: False
  std_magnification: 3

# model architecture
model:
  noisy_net: False
  action_embedding: True
  action_embedding_dim: 16
  block_type: resnet
  down_sample: True
  state_norm: False
  value_prefix: False
  value_target: bootstrapped
  GAE_max_steps: 15
  dynamic_type: None
  init_zero: True
  num_blocks: 1
  num_channels: 64
  reduced_channels: 16

  projection_layers: [1024, 1024]
  prjection_head_layers: [256, 1024]

  fc_layers: [32]
  lstm_hidden_size: 512
  lstm_horizon_len: 5
  value_ensumble: 1

  policy_distribution: squashed_gaussian
  policy_loss_type: reanalyze
  policy_action_num: 4
  random_action_num: 12
  random_type: std

  reward_support:
    range: [-2, 2]
    scale: 0.01
    env: DMC
    bins: 51
    type: support
  value_support:
    range: [-299, 299]
    scale: 0.5
    env: DMC
    bins: 51
    type: support

# worker process allocation
actors:
  data_worker: 2
  batch_worker: 8

# mlflow
mlflow:
  project: 'ez-v2-release'
  tag: 'DMC-state'
